# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_motorista', models.CharField(max_length=10)),
                ('dui', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_punto', models.CharField(max_length=10)),
                ('ubicacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLlegada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_registro', models.CharField(max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('num_pasajeros', models.IntegerField(blank=True, default=0, null=True)),
                ('cant_dinero', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('punto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppTrans.PuntoControl')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsablePunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_responsable', models.CharField(max_length=10)),
                ('dui', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_unidad', models.CharField(max_length=10)),
                ('ruta', models.IntegerField(default=0)),
                ('placa', models.CharField(max_length=15)),
                ('nombre_mote', models.CharField(default='No tiene nombre', max_length=20)),
                ('motorista', models.OneToOneField(blank=True, default='No Asignado', null=True, on_delete=django.db.models.deletion.CASCADE, to='AppTrans.Motorista')),
            ],
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppTrans.ResponsablePunto'),
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppTrans.UnidadTransporte'),
        ),
        migrations.AddField(
            model_name='puntocontrol',
            name='responsable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppTrans.ResponsablePunto'),
        ),
    ]
