# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-13 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrans', '0002_auto_20190713_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadtransporte',
            name='ruta',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
