# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-14 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrans', '0004_motorista_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsablepunto',
            name='direccion',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
