# Generated by Django 2.1.9 on 2019-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_motorista', models.CharField(max_length=10)),
                ('dui', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsablePunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_responsable', models.CharField(max_length=10)),
                ('dui', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
