# Generated by Django 2.1.9 on 2019-06-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motorista',
        ),
        migrations.DeleteModel(
            name='ResponsablePunto',
        ),
    ]
