# Generated by Django 2.1.9 on 2019-06-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transporte', '0002_auto_20190610_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_motorista', models.CharField(max_length=10)),
                ('dui', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsablePunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_responsable', models.CharField(max_length=10)),
                ('dui', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
    ]
