# Generated by Django 2.1.9 on 2019-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_motorista_responsablepunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLlegada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('num_pasajeros', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_unidad', models.CharField(max_length=10)),
                ('placa', models.CharField(max_length=15)),
                ('nombre_mote', models.CharField(max_length=20)),
            ],
        ),
    ]
