# Generated by Django 2.1.9 on 2019-06-17 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_registrollegada_unidadtransporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_punto', models.CharField(max_length=10)),
                ('nombre_punto', models.CharField(max_length=25)),
                ('ubicacion', models.CharField(max_length=60)),
                ('responsable', models.OneToOneField(on_delete=False, to='transporte.ResponsablePunto')),
            ],
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='cod_registro',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='registrollegada',
            name='unidad',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='transporte.UnidadTransporte'),
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='motorista',
            field=models.OneToOneField(default=False, on_delete=False, to='transporte.Motorista'),
        ),
        migrations.AlterField(
            model_name='registrollegada',
            name='num_pasajeros',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='registrollegada',
            name='responsable',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='transporte.ResponsablePunto'),
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='cod_unidad',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='nombre_mote',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='placa',
            field=models.CharField(default=False, max_length=15),
        ),
    ]
